### ISSUE TITLE
NumPy version related bug

### ISSUE THREAD

**Issue by marieyao** [zhujun98/foamgraph#32]
2023-01-27 15:47:35,096 - qapp.py - INFO - Data 24953 processed
2023-01-27 15:47:35,192 - qapp.py - INFO - Data 24954 processed
Traceback (most recent call last):
  File "/Users/justmercy/opt/anaconda3/envs/foamlight/lib/python3.9/site-packages/foamgraph/pyqtgraph_be/GraphicsScene/GraphicsScene.py", line 575, in mouseMoveEvent
    if self.sendDragEvent(
  File "/Users/justmercy/opt/anaconda3/envs/foamlight/lib/python3.9/site-packages/foamgraph/pyqtgraph_be/GraphicsScene/GraphicsScene.py", line 686, in sendDragEvent
    item.mouseDragEvent(event)
  File "/Users/justmercy/opt/anaconda3/envs/foamlight/lib/python3.9/site-packages/foamgraph/pyqtgraph_be/graphicsItems/AxisItem.py", line 1134, in mouseDragEvent
    return lv.mouseDragEvent(ev, axis=1)
  File "/Users/justmercy/opt/anaconda3/envs/foamlight/lib/python3.9/site-packages/foamgraph/pyqtgraph_be/graphicsItems/ViewBox/ViewBox.py", line 1178, in mouseDragEvent
    mouseEnabled = np.array(self.state['mouseEnabled'], dtype=np.float)
  File "/Users/justmercy/opt/anaconda3/envs/foamlight/lib/python3.9/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'
zsh: abort      python align_fit.py

**Comment by zhujun98** [comment]
Thanks @marieyao !
